[phases.setup]
aptPkgs = ["ffmpeg", "poppler-utils", "tesseract-ocr", "tesseract-ocr-rus", "tesseract-ocr-eng"]
cmds = ["pip install setuptools", "pip config set global.no-build-isolation true"]

[start]
cmd = "python main.py"
