[phases.setup]
aptPkgs = ["ffmpeg", "poppler-utils", "tesseract-ocr", "tesseract-ocr-rus", "tesseract-ocr-eng"]

[phases.install]
cmds = [
  "pip install setuptools",
  "pip install --no-build-isolation openai-whisper==20240930",
  "pip install -r requirements.txt",
  "pip cache purge"
]

[start]
cmd = "python main.py"
